# Generated by manual edit for DocumentID change to CharField(8)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patientconsultations_tests_treatmentplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DocumentID',
            field=models.CharField(max_length=8),
        ),
    ]
