# Generated by Django 5.2.5 on 2025-09-28 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_documentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triagerecords',
            name='consultation',
        ),
        migrations.AddField(
            model_name='patientconsultations',
            name='triage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='patients.triagerecords'),
        ),
    ]
